name: Lint

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v8

      - name: Ruff format
        run: uvx ruff format --check src/ examples/

      - name: Ruff lint
        run: uvx ruff check src/ examples/